import { PRODUCTS } from '../data/products.js';
import { qs, qsa } from '../core/dom.js';
import { state } from '../core/state.js';
import { toggleFavorite } from './favorites.js';
const imageFor = product => 'https://tse2.mm.bing.net/th?q=' + encodeURIComponent(product.brand + ' ' + product.name + ' official perfume bottle luxury campaign advertising photo elegant beautiful background product only no people no hands no box') + '&w=700&h=700&c=7&rs=1&p=0&dpr=1.5&pid=1.7&mkt=ru-RU&adlt=strict';
const priceValue = product => Number((String(product.price).match(/\d+/) || [Infinity])[0]);
const card = product => { const active = state.favorites.has(product.id); return `<article class="product-card" data-product-id="${product.id}" tabindex="0" role="button" aria-label="Открыть описание ${product.name}"><div class="product-card__media">${product.badge ? `<span class="product-card__badge">${product.badge}</span>` : ''}<button type="button" class="product-card__favorite ${active ? 'active' : ''}" data-favorite="${product.id}" aria-pressed="${active}" aria-label="${active ? 'Удалить из избранного' : 'Добавить в избранное'}">${active ? '♥' : '♡'}</button><img class="product-card__image" src="${imageFor(product)}" alt="Флакон аромата ${product.name}" loading="lazy" decoding="async"><div class="product-card__fallback" hidden>A&M PARFUM<br><strong>${product.name}</strong></div></div><div class="product-card__body"><span class="product-card__brand">${product.brand}</span><h3>${product.name}</h3><span class="product-card__meta">${product.gender}</span><div class="product-card__footer"><span>${product.volume}</span><button type="button" class="product-card__price-button" data-price="${product.id}">Узнать цену</button></div></div></article>`; };
function filtered() { const query = qs('#search').value.toLowerCase().trim(), gender = qs('#gender').value; return PRODUCTS.filter(product => (!query || (product.name + ' ' + product.brand).toLowerCase().includes(query)) && (gender === 'all' || product.gender === gender)); }
export function renderCatalog() { let items = filtered(); const sort = qs('#sort').value; if (sort === 'name-asc') items.sort((a,b) => a.name.localeCompare(b.name,'ru')); if (sort === 'name-desc') items.sort((a,b) => b.name.localeCompare(a.name,'ru')); if (sort === 'price-asc') items.sort((a,b) => priceValue(a)-priceValue(b)); if (sort === 'price-desc') items.sort((a,b) => priceValue(b)-priceValue(a)); qs('#grid').innerHTML = items.slice(0,state.shown).map(card).join(''); qs('#loadMore').style.display = state.shown >= items.length ? 'none' : 'inline-flex'; }
export function initCatalog() {
  ['search','gender','sort'].forEach(id => qs('#'+id).addEventListener(id === 'search' ? 'input' : 'change', () => { state.shown=24; renderCatalog(); }));
  qs('#reset').addEventListener('click', () => { qs('#search').value=''; qs('#gender').value='all'; qs('#sort').value='default'; state.shown=24; renderCatalog(); });
  qs('#loadMore').addEventListener('click', () => { state.shown += 24; renderCatalog(); });
  qs('#grid').addEventListener('click', event => { const favorite = event.target.closest('[data-favorite]'); if (favorite) { event.preventDefault(); event.stopPropagation(); toggleFavorite(Number(favorite.dataset.favorite), favorite); return; } const price = event.target.closest('[data-price]'); if (price) { event.stopPropagation(); const product=PRODUCTS.find(item=>item.id===Number(price.dataset.price)); window.open('https://wa.me/79621441441?text='+encodeURIComponent('Здравствуйте! Подскажите цену и наличие: '+product.brand+' — '+product.name),'_blank'); return; } const productCard=event.target.closest('.product-card'); if(productCard) window.openProductDetail(Number(productCard.dataset.productId), productCard.querySelector('.product-card__image')?.src); });
  renderCatalog();
}
